#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

GO_BIN="${GO_BIN:-go}"
OUT_FILE="${OUT_FILE:-THIRD_PARTY_NOTICES.md}"
PLATFORMS="${PLATFORMS:-linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64}"
GENERATED_ON="${GENERATED_ON:-$(date -u +%Y-%m-%d)}"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

modules_tsv="$tmp_dir/modules.tsv"
licenses_tsv="$tmp_dir/licenses.tsv"
output_tmp="$tmp_dir/THIRD_PARTY_NOTICES.md"

license_override() {
	case "$1" in
		github.com/cloudwego/eino-ext/components/model/openai) echo "Apache-2.0" ;;
		github.com/cloudwego/eino-ext/libs/acl/openai) echo "Apache-2.0" ;;
		github.com/mattn/go-localereader) echo "MIT" ;;
		*) return 1 ;;
	esac
}

detect_license_from_file() {
	local source_file="$1"

	if grep -Eiq 'apache license|apache software foundation|apache-2\.0|apache 2\.0' "$source_file"; then
		echo "Apache-2.0"
		return 0
	fi
	if grep -Eiq 'mit license|permission is hereby granted, free of charge|^mit$' "$source_file"; then
		echo "MIT"
		return 0
	fi
	if grep -Eiq 'isc license|permission to use, copy, modify, and/or distribute this software for any purpose with or without fee' "$source_file"; then
		echo "ISC"
		return 0
	fi
	if grep -Eiq 'bsd 3-clause' "$source_file"; then
		echo "BSD-3-Clause"
		return 0
	fi
	if grep -Eiq 'bsd 2-clause' "$source_file"; then
		echo "BSD-2-Clause"
		return 0
	fi
	if grep -Eiq 'redistribution and use in source and binary forms' "$source_file"; then
		if grep -Eiq 'neither the name' "$source_file"; then
			echo "BSD-3-Clause"
		else
			echo "BSD-2-Clause"
		fi
		return 0
	fi

	return 1
}

find_license_source() {
	local module_dir="$1"
	local source_file

	source_file="$(find "$module_dir" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'COPYING*' \) -type f | sort | head -n 1 || true)"
	if [[ -n "$source_file" ]]; then
		echo "$source_file"
		return 0
	fi

	source_file="$(find "$module_dir" -maxdepth 1 -iname 'README*' -type f | sort | head -n 1 || true)"
	if [[ -n "$source_file" ]]; then
		echo "$source_file"
		return 0
	fi

	return 1
}

: >"$modules_tsv"
for platform in $PLATFORMS; do
	goos="${platform%/*}"
	goarch="${platform#*/}"
	GOOS="$goos" GOARCH="$goarch" "$GO_BIN" list -deps -f '{{with .Module}}{{if and .Path (ne .Path "delve-shell")}}{{.Path}}{{"\t"}}{{.Version}}{{end}}{{end}}' ./... >>"$modules_tsv"
done

sort -u "$modules_tsv" | sed '/^$/d' >"$tmp_dir/modules.sorted.tsv"

: >"$licenses_tsv"
while IFS=$'\t' read -r module version; do
	module_info="$("$GO_BIN" list -m -f '{{.Dir}}{{"\t"}}{{with .Replace}}{{.Path}}{{"\t"}}{{.Version}}{{end}}' "$module")"
	IFS=$'\t' read -r module_dir replace_path replace_version <<<"$module_info"

	license=""
	if ! license="$(license_override "$module" 2>/dev/null)"; then
		if source_file="$(find_license_source "$module_dir")"; then
			license="$(detect_license_from_file "$source_file" || true)"
		fi
	fi
	if [[ -z "$license" ]]; then
		license="UNKNOWN"
	fi

	display_version="$version"
	if [[ -n "${replace_path:-}" && -n "${replace_version:-}" ]]; then
		display_version="${display_version} (replaced by ${replace_path} ${replace_version})"
	fi

	printf '%s\t%s\t%s\n' "$module" "$display_version" "$license" >>"$licenses_tsv"
done <"$tmp_dir/modules.sorted.tsv"

unknown_modules="$(awk -F '\t' '$3 == "UNKNOWN" {print $1 "\t" $2}' "$licenses_tsv")"
if [[ -n "$unknown_modules" ]]; then
	echo "unrecognized dependency license(s):" >&2
	printf '%s\n' "$unknown_modules" >&2
	exit 1
fi

mit_count="$(awk -F '\t' '$3 == "MIT" {count++} END {print count + 0}' "$licenses_tsv")"
apache_count="$(awk -F '\t' '$3 == "Apache-2.0" {count++} END {print count + 0}' "$licenses_tsv")"
bsd3_count="$(awk -F '\t' '$3 == "BSD-3-Clause" {count++} END {print count + 0}' "$licenses_tsv")"
bsd2_count="$(awk -F '\t' '$3 == "BSD-2-Clause" {count++} END {print count + 0}' "$licenses_tsv")"
isc_count="$(awk -F '\t' '$3 == "ISC" {count++} END {print count + 0}' "$licenses_tsv")"

{
	echo "# Third-Party Notices"
	echo
	echo "\`delve-shell\` is licensed under Apache-2.0."
	echo
	echo "This file is generated by \`scripts/update-third-party-notices.sh\`. It provides a best-effort summary of the Go modules reachable from the application build targets and is not legal advice."
	echo
	echo "Dependency data in this file was derived from the union of \`go list -deps ./...\` across these target platforms on ${GENERATED_ON}: \`${PLATFORMS}\`."
	echo
	echo "All currently reachable modules use permissive licenses:"
	echo
	echo "- \`MIT\`: ${mit_count} modules"
	echo "- \`Apache-2.0\`: ${apache_count} modules"
	echo "- \`BSD-3-Clause\`: ${bsd3_count} modules"
	echo "- \`BSD-2-Clause\`: ${bsd2_count} modules"
	if [[ "$isc_count" != "0" ]]; then
		echo "- \`ISC\`: ${isc_count} modules"
	fi
	echo
	echo "Notes:"
	echo
	echo "- \`github.com/cloudwego/eino-ext/components/model/openai\` and \`github.com/cloudwego/eino-ext/libs/acl/openai\` are treated as \`Apache-2.0\` based on the upstream \`github.com/cloudwego/eino-ext\` repository license."
	echo "- \`github.com/goph/emperror\` is replaced in \`go.mod\` by \`emperror.dev/emperror v0.19.0\`; that replacement is called out in the version column below."
	echo
	echo "## Go Modules"
	echo
	echo "| Module | Version | License |"
	echo "|---|---:|---|"
	awk -F '\t' '{gsub(/\|/, "\\|", $1); printf("| `%s` | `%s` | `%s` |\n", $1, $2, $3)}' "$licenses_tsv"
} >"$output_tmp"

mv "$output_tmp" "$OUT_FILE"
